src/apps/stations/urls.py
# ----------------------------------------------------------------------------
# Copyright (c) 2026 University of Alabama, Digital Forensics and Control Systems Security Lab (DCSL)
# All rights reserved.
#
# Distributed under the terms of the BSD 3-clause license.
#
# The full license is in the LICENSE file, distributed with this software.
# ----------------------------------------------------------------------------
from django.urls import path, re_path
from . import views
from .views import StationListView, MyStationsListView


urlpatterns = [
    #path('stations/', views.station_list_view, name="stations"),
    path('stations/', StationListView.as_view(), name="stations"),
    path('add/', views.add_station_view, name="add_station"),
    path('update/<int:id>/', views.update_station_view, name="station_update"),
    #path('my_stations_list/', views.my_stations_list_view, name="my_stations_list"),
    path('my_stations_list/', MyStationsListView.as_view(), name="my_stations_list"),
    path('station_details/<int:id>/', views.station_details_view, name="station_details"),
# urls.py
path("station_instruments/<int:id>/", views.station_instrument_view, name="station_instruments"),
    ]


#url paths updated to use current django url paths instead of regular expressions

src/psws/urls.py
# ----------------------------------------------------------------------------
# Copyright (c) 2026 University of Alabama, Digital Forensics and Control Systems Security Lab (DCSL)
# All rights reserved.
#
# Distributed under the terms of the BSD 3-clause license.
#
# The full license is in the LICENSE file, distributed with this software.
# ----------------------------------------------------------------------------
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from apps.api import views as apiviews
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

favicon_view = RedirectView.as_view(url= settings.BASE_DIR /'static/img/favicon.ico', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stations/', apiviews.StationList.as_view(), name='stationList'),
    path('heartbeat/', apiviews.StationHeartbeat.as_view(), name='heartbeat'),
    path('stop/', apiviews.StationStop.as_view(), name='stop'),
    path('accounts/', include('apps.accounts.urls')),
    path('', include('apps.accounts.urls')),
    path('stations/', include('apps.stations.urls')),
    path('favicon.ico', favicon_view),
    path('observations/', include('apps.observations.urls')),
    path('instruments/', include('apps.instruments.urls')),
    path('analysis/', include('apps.analysis.urls')),
    path("", include("apps.core.urls")),
] +  staticfiles_urlpatterns()

src/apps/stations/models.py
# ----------------------------------------------------------------------------
# Copyright (c) 2026 University of Alabama, Digital Forensics and Control Systems Security Lab (DCSL)
# All rights reserved.
#
# Distributed under the terms of the BSD 3-clause license.
#
# The full license is in the LICENSE file, distributed with this software.
# ----------------------------------------------------------------------------
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime

# Create your models here.

class Station(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    station_id = models.CharField("ID", max_length=10, default='N000000')
    station_pass = models.CharField(max_length=32, null=True, blank=True)
    nickname = models.CharField(max_length=50)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    grid = models.CharField(max_length=6, null=True)
    elevation = models.FloatField(blank=True, null=True) 
    antenna_1 = models.CharField(max_length=64, null=True) 
    antenna_2 = models.CharField(max_length=64, blank=True)
    street_address = models.CharField(max_length=75, blank=True)
    city = models.CharField(max_length=75, blank=True)
    state = models.CharField(max_length=15, blank=True)
    postal_code = models.CharField(max_length=15, blank=True) #must support international values
    phone_number = models.CharField(max_length=20, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)

    last_rID = models.IntegerField(default=0)
    last_alive = models.DateTimeField(null=True)

    offlineNotify = models.BooleanField("Station Offline Notification", null=True, blank=True)

    class StationStatus(models.TextChoices):
           ONLINE =  "Online",
           POSSIBLYONLINE =  "PossiblyOnline",
           OFFLINE =  "Offline"
    
    station_status = models.CharField(
            max_length=20,
            choices=StationStatus.choices,
            default=StationStatus.OFFLINE,
    )

    def __str__(self):
        return self.nickname

src/apps/stations/views.py
# ----------------------------------------------------------------------------
# Copyright (c) 2026 University of Alabama, Digital Forensics and Control Systems Security Lab (DCSL)
# All rights reserved.
#
# Distributed under the terms of the BSD 3-clause license.
#
# The full license is in the LICENSE file, distributed with this software.
# ----------------------------------------------------------------------------
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView
from datetime import datetime
from apps.stations.models import Station
from apps.stations.forms import StationCreationForm
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django_tables2 import SingleTableView
from django.conf import settings

import maidenhead as mh
from .tables import StationTable, FilteredStationTable, StationUserTable, StationInstrumentTable
from .forms import EditStationForm
from .tokens import station_activation_token
from .forms import StationUserFilterForm

from apps.instruments.models import Instrument
from apps.instruments.tables import InstrumentTable
from apps.observations.models import Observation

import os, sys
import logging
logger = logging.getLogger(__name__)

from django.http import HttpResponse


@method_decorator(login_required, name='dispatch')
# Display a list of the currently logged in user's stations
class MyStationsListView(SingleTableView):
    #To filter the queryset by user, must use a method to access the request object
    def get_queryset(self):
        return Station.objects.filter(user=self.request.user)

    table_class = FilteredStationTable
    template_name = 'my_stations_list.html'
    paginate_by = 4




# Display the list of all registered stations
class StationListView(SingleTableView):
    template_name = 'stations.html'
    paginate_by = 4
    def get_table_class(self):
        if(self.request.user.is_superuser):    
            if self.request.GET.get('swap') == '1':
                return StationUserTable
        return StationTable 

    def get_queryset(self):
        qs = Station.objects.all()
        if self.request.user.is_superuser and self.request.GET.get('swap') == '1':
            usename = self.request.GET.get('user', "").strip()
            if usename:
                qs = qs.filter(user__username__istartswith=usename)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['swap'] = self.request.GET.get('swap') == '1'
        context['filter_form'] = StationUserFilterForm(self.request.GET)
        return context

@login_required
def station_instrument_view(request, id):
    if not request.user.is_superuser:
        return redirect('stations')
    instruments = (
        Instrument.objects
        .filter(station__user__id=id)  # only instruments for stations owned by this user
        .select_related("station", "instrumenttype", "station__user")
    )

    table = StationInstrumentTable(instruments)
    table.paginate(page=request.GET.get("page", 1), per_page=10)

    return render(request, "station_instruments.html", {
        "table": table,
    })

@login_required
# Display more detailed information about a station
def station_details_view(request, id=None):
    station = get_object_or_404(Station, id=id, user=request.user)

    context = {'station': station}
    table = InstrumentTable(Instrument.objects.filter(station_id=id))
    table.paginate(page=request.GET.get("page", 1), per_page=8)
    return render(request, 'station_details.html', 
        {'station': station, 'table': table}
            )

@login_required
# Allow a user to register a new station
def add_station_view(request):
    if request.method == "POST":
        form = StationCreationForm(request.POST)
        if form.is_valid():
            station = form.save(commit=False)
            station.user_id = request.user.id
            
            # Determine new station's ID number
            try:
                new_id_number = Station.objects.latest('create_date').id + 1
            except ObjectDoesNotExist:
                new_id_number = 1
            
            station.station_id = 'S' + str(new_id_number).zfill(6)
            station.station_pass = station_activation_token.make_token(request.user)
            station.station_pass = station.station_pass.replace('-', station.station_pass[0])[4:36]
            station.nickname = form.cleaned_data.get('nickname')
            station.grid = form.cleaned_data.get('grid')
            try:
                station.latitude =  mh.to_location(station.grid, center=True)[0]
                station.longitude = mh.to_location(station.grid, center=True)[1]
            except Exception as e:
                text = "You entered an invalid grid square value. For help with this see <a href='https://www.levinecentral.com/ham/grid_square.php'>here.</a>"
                return HttpResponse(text)
            station.elevation = form.cleaned_data.get('elevation')
            station.antenna_1 = form.cleaned_data.get('antenna_1')
            station.antenna_2 = form.cleaned_data.get('antenna_2')
            station.street_address = form.cleaned_data.get('street_address')
            station.city = form.cleaned_data.get('city')
            station.state = form.cleaned_data.get('state')
            station.postal_code = form.cleaned_data.get('postal_code')
            station.phone_number = form.cleaned_data.get('phone_number')
            station.create_date = datetime.now()
            station.save()
            os.system('sudo ' + str(settings.BASE_DIR) + '/scripts/ingest/stationcreation4.sh ' + station.station_id + ' ' + station.station_pass)
            return redirect('stations')
    else:
        form = StationCreationForm()

    return render(request, 'add_station.html', {'form': form})

@login_required
# Allow a user to edit the data of a specific station
def update_station_view(request, id=None):
    station = get_object_or_404(Station, id=id, user=request.user)

    if request.method == 'POST':
        form = EditStationForm(request.POST, request.FILES, instance=station)

        if request.POST.get("del-button"):
          instrQS = Instrument.objects.filter(station_id=station.id)
          if instrQS.count() > 0:   # this station has instrument(s), deny the deletion
            messages.error(request, "(!) YOU CAN ONLY DELETE THIS STATION AFTER DELETING ITS INSTRUMENT(S).")
            return render(request, 'station_update.html', {'form': form, 'station': station})
          station.delete()
          return redirect('my_stations_list')

        if request.POST.get("del-button"):
            instrQS = Instrument.objects.filter(station_id=station.id)
            if instrQS.count() > 0:   # this station has instrument(s), deny the deletion
                messages.error(request, "(!) YOU CAN ONLY DELETE THIS STATION AFTER DELETING ITS INSTRUMENT(S).")
                return render(request, 'station_update.html', {'form': form, 'station': station})
            station.delete()
            return redirect('my_stations_list')

        if form.is_valid():
            station.nickname = form.cleaned_data.get('nickname')
            station.grid = form.cleaned_data.get('grid')
            station.latitude = mh.to_location(station.grid,center=True)[0]
            station.longitude = mh.to_location(station.grid,center=True)[1]
            station.elevation = form.cleaned_data.get('elevation')
            station.antenna_1 = form.cleaned_data.get('antenna_1')
            station.antenna_2 = form.cleaned_data.get('antenna_2')
            station.street_address = form.cleaned_data.get('street_address')
            station.city = form.cleaned_data.get('city')
            station.state = form.cleaned_data.get('state')
            station.postal_code = form.cleaned_data.get('postal_code')
            station.phone_number = form.cleaned_data.get('phone_number')
            station.save()
            messages.success(request, 'Your station has been updated!')
            return render(request, 'station_update.html', {'form': form, 'station': station})
        else:
            form = EditStationForm(instance=station)
            messages.error(request, 'Issue updating information.')
            return render(request, 'station_update.html', {'form': form, 'station': station})
    else:
        form = EditStationForm(instance=station)
        instrQS = Instrument.objects.filter(station_id=station.id)
        if instrQS.count() > 0:  # if this station has instrument(s) issue warning
            messages.warning(request, "(!) ONE OR MORE INSTRUMENT(S) UNDER THIS STATION. You must delete them before deleting station.")

        return render(request, 'station_update.html', {'form': form, 'station': station})

@login_required
# Allow user to add a new instrument
def add_instrument_view(request, id=id):
    if request.method == "POST":
        form = InstrumentCreationForm(request.POST)
        if form.is_valid():
            instrument = form.save(commit=False)
            instrument.station_id = id

            instrument.instrument = form.cleaned_data.get('instrument')
            instrument.dateAdded  = form.cleaned_data.get('date_added')
            instrument.nickname   = form.cleaned_data.get('nickname')
            instrument.serialNo   = form.cleaned_data.get('serial_no')
            instrument.status     = form.cleaned_data.get('status')

            instrument.save()
            return redirect('instruments')
    else:
        form = InstrumentCreationForm()

    return render(request, 'add_instrument.html', {'form': form})

src/apps/stations/templates/add_station.html
{% extends "base_stations.html" %}
@login_required
def station_instrument_view(request):
    instruments = Instrument.objects.select_related("station", "instrumenttype", "station__user")
    table = StationInstrumentTable(instruments)
    table.paginate(page=request.GET.get("page", 1), per_page=10)
    return render(request, "station_instruments.html", {"table": table})
{% load crispy_forms_tags %}

{% block title %}
<h2 class="text-center">Add Station Form</h2>
{% endblock title %}

{% block main %}
<p>IMPORTANT: All information on this page except for station nickname and Maidenhead grid square is optional.
For grid square, we need a minimum of a 4-character grid (e.g., EM64). If you wish to omit entry of data in
any field, leave it blank. Anything else you enter becomes public information. (Amateur radio operators: we suggest
you use what is on file with the FCC, as it is already in the public record). We collect this information
so that we can give you credit if your data is used in publications such as peer-reviewed journals. Mandatory fields are marked with an asterisk (*).
</p>


<!--<form method="post">
	{% csrf_token %}
	{% for field in form %}
	  <p>
	    {{ field.label_tag }} {% if field.field.required %}*{% endif %} <br>
	    {{ field }}
	    {% if field.help_text %}
	      <small style="color: grey">{{ field.help_text }}</small>
	    {% endif %}
	    {% for error in field.errors %}
	      <p style="color: red">{{ error }}</p>
	    {% endfor %} 
	  </p>
	{% endfor %}
	<button type="submit">Add Station</button>
</form>-->
<form method="post">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-primary btn-block">Add Station</button>
</form>
<br>
<form action="{% url 'stations' %}" method="get">
	{% csrf_token %}
	<button type="submit" class="btn btn-danger btn-block"> Cancel</button>
</form>
<br>
<br>
{% endblock main %}

src/apps/stations/templates/base.html
{% load static %}
<!doctype  html>
<html  lang="en">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>Personal Space Weather Station Server</title>

<script src='https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css' rel='stylesheet' />
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
}

ul.Menu{
  background-color: #333;
}

li {
  float: left;
  border-right:1px solid #bbb;
}

li:last-child {
  border-right: none;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) {
  background-color: #111;
}

.active {
  background-color: #04AA6D;
}
</style>

<body>
  <div  class="container">
    <div  class="row justify-content-center">
     <div class="col-10">
      <h1  class="text-center">Personal Space Weather Station</h1>
       <h2 class="text-center">Central Control System</h2>
      {% block title %}
      {% endblock title %}
      	<ul>
		<li><a class="active" href="#home">Home</a></li>
		<li><a href="#stations">Stations</a></li>
		<li><a href="#observations">Observations</a></li>
		<li><a href="/login/">Log In</a></li>
		<li><a href="/signup/">Register your station</a></li>
		<li style="float:right"><a href="/about/">About!</a></li>
	</ul>
      {% block main %}
      {% endblock main %}
     </div>
    </div>
  </div>
</body>
</html>

src/apps/stations/templates/base_stations.html
{% load static %}
<!doctype  html>
<html  lang="en">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>Personal Space Weather Station Server</title>

<script src='https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css' rel='stylesheet' />
<style>
.header {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

ul.a {list-style-type: circle;}

li {
  float: left;
  border-right:1px solid #bbb;
}

li:last-child {
  border-right: none;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) {
  background-color: #111;
  text-decoration: none;
  color: white;
}

.pagination li:not(.active) {
  background-color: #333
}

.active {
  background-color: #04AA6D;
}

.details {
  float: none;
  border-right: none;
}
</style>

<body>
  <div  class="container">
    <div  class="row justify-content-center">
     <div class="col-10">
      <h1  class="text-center">Personal Space Weather Station</h1>
       <h2 class="text-center">Central Control System</h2>
      {% block title %}
      {% endblock title %}
      {% if user.is_authenticated %}
        <ul class="Menu">
          <li><a href="/home">Home</a></li>
          <li><a class="active" href="/stations/stations">Stations</a></li>
          <li><a href="/observations/observation_list">Observations</a></li>
          <li><a href="/analysis/analysis">Analysis</a></li>
          <li><a href="/user_list">Users</a></li>
          <li>
            <form method="post" action="{% url 'logout' %}" style="display: inline;">
              {% csrf_token %}
              <button type="submit" style="background: none; border: none; color: white; text-align: center; padding: 14px 16px; text-decoration: none; display: block; cursor: pointer; font-family: inherit; font-size: inherit;">Log Out</button>
            </form>
          </li>
          <li><a href="/signup/">Register your station</a></li>
          <li><a href="{% url 'profile' %}">{{ request.user.username }}</a></li>
          <li style="float:right"><a href="/about/">About</a></li>
        </ul>
        {% else %}
        <ul class="Menu">
          <li><a href="/home">Home</a></li>
          <li><a class="active" href="/stations/stations">Stations</a></li>
          <li><a href="/observations/observation_list">Observations</a></li>
          <li><a href="/analysis/analysis">Analysis</a></li>
          <li><a href="/user_list">Users</a></li>
          <li><a href="/login/">Log In</a></li>
          <li><a href="/signup/">Register your station</a></li>
          <li style="float:right"><a href="/about/">About</a></li>
        </ul>
        {% endif %}
      {% block main %}
      {% endblock main %}
     </div>
    </div>
  </div>
</body>
</html>

src/apps/stations/templates/grid_error.html
{% extends "base_stations.html" %}

{% block title %}<h1 class="text-center">Stations</h1>{% endblock title %}

{% block main %}
{% load render_table from django_tables2 %}

You entered an invalid Maidenhead grid square value. If you are uncertain on how to
set your grid square location, see <a href="https://www.levinecentral.com/ham/grid_square.php"> here.</a>

<style>
table {
        width: 1000px;
        border: 5px solid black;
}
</style>
<!--
th {
        border: 5px solid black;
        text-align: center;
}
tr, td {
        border: 3px solid #dddddd;
        text-align: center;
}
-->
<!--<h1 class="text-center">Stations</h1>-->
<div>
        <a href="{% url 'my_stations_list' %}">View your stations</a>
</div>
<div>
        <a href="{% url 'add_station' %}">Add new station</a>
</div>
<br>

<div>
        {% render_table table %}
</div>

<!--
<table>
        <tr>
                <th>ID</th>
                <th>User</th>
                <th>Nickname</th>
                <th>Grid</th>
                <th>Elevation</th>
                <th>Antenna 1</th>
                <th>Antenna 2</th>
        </tr>
        {% for station in mag_stations %}
        <tr>
                <td>{{station.station_id}}</td>
                <td>{{station.user.username}}</td>
                <td>{{station.nickname}}</td>
                <td>{{station.grid}}</td>
                <td>{{station.elevation}}</td>
                <td>{{station.antenna_1}}</td>
                <td>{{station.antenna_2}}</td>
        </tr>
        {% endfor %}
</table>
-->

<div>
        <a href="{% url 'my_stations_list' %}">View your stations</a>
</div>
<div>
        <a href="{% url 'add_station' %}">Add new station</a>
</div>

{% endblock main %}

src/apps/stations/templates/my_stations_list.html
{% extends "base_stations.html" %}

{% block title %} 
<h1 class="text-center">{{request.user.username}}'s Stations</h1>
{% endblock title %}

{% block main %}
{% load render_table from django_tables2 %}

<style>
table {
	width: 1000px;
	border: 5px solid black;
}
</style>

<!--
th {
	border: 5px solid black;
	text-align: center;
}
tr, td {
	border: 3px solid #dddddd;
	text-align: center;
}
</style>
-->

<div style="padding-top: 10px;">
    <!-- Add Station -->
	<form action="{% url 'add_station' %}" method="GET">
		{% csrf_token %}
		<button type="submit">Add New Station</button>
	</form>
</div>

<div>
To add a new instrument, click on the station's ID.
</div>
<div>
To look at the details of a station (or edit it), click on its link in the ID column
</div>
<br>

<div>
	{% render_table table %}
</div>

<!--
<table>
	<tr>
		<th>ID</th>
		<th>User</th>
		<th>Nickname</th>
		<th>Grid</th>
		<th>Elevation</th>
		<th>Antenna 1</th>
		<th>Antenna 2</th>
	</tr>
	{% for station in request.user.station_set.all %}
	<tr>
		<td><a href="{% url 'station_details' id=station.id %}">{{station.station_id}}</a></td>
		<td>{{station.user.username}}</td>
		<td>{{station.nickname}}</td>
		<td>{{station.grid}}</td>
		<td>{{station.elevation}}</td>
		<td>{{station.antenna_1}}</td>
		<td>{{station.antenna_2}}</td>
	</tr>
	{% endfor %}
</table>
-->
<div style="padding-top: 10px;">
    <!-- Back to Stations page-->
	<form action="{% url 'stations' %}" method="GET">
		{% csrf_token %}
		<button type="submit">Back</button>
	</form>
</div>

<div class="pagination">
    <span class="step-links">
	{% if page_obj.has_previous %}
	    <a href="?page=1">&laquo; first</a>
	    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
	{% endif %}

	<span class="current">
	    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
	</span>

	{% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">next</a>
	    <a href="?page={{ page_obj.paginator.num_pages }}">kast &raquo;</a>
	{% endif %}
    </span>
</div>

{% endblock main %}

src/apps/stations/templates/my_stations_list_orig.html
{% extends "base_stations.html" %}

{% block title %} 
<h1 class="text-center">{{request.user.username}}'s Stations</h1>
{% endblock title %}

{% block main %}
{% load render_table from django_tables2 %}

<style>
table {
	width: 1000px;
	border: 5px solid black;
}
</style>

<!--
th {
	border: 5px solid black;
	text-align: center;
}
tr, td {
	border: 3px solid #dddddd;
	text-align: center;
}
</style>
-->

<div style="padding-top: 10px;">
    <!-- Add Station -->
	<form action="{% url 'add_station' %}" method="GET">
		{% csrf_token %}
		<button type="submit">Add New Station</button>
	</form>
</div>

<div>
To add a new instrument, click on the station's ID.
</div>
<div>
To look at the details of a station (or edit it), click on its link in the ID column
</div>
<br>

<div>
	{% render_table table %}
</div>

<!--
<table>
	<tr>
		<th>ID</th>
		<th>User</th>
		<th>Nickname</th>
		<th>Grid</th>
		<th>Elevation</th>
		<th>Antenna 1</th>
		<th>Antenna 2</th>
	</tr>
	{% for station in request.user.station_set.all %}
	<tr>
		<td><a href="{% url 'station_details' id=station.id %}">{{station.station_id}}</a></td>
		<td>{{station.user.username}}</td>
		<td>{{station.nickname}}</td>
		<td>{{station.grid}}</td>
		<td>{{station.elevation}}</td>
		<td>{{station.antenna_1}}</td>
		<td>{{station.antenna_2}}</td>
	</tr>
	{% endfor %}
</table>
-->
<div style="padding-top: 10px;">
    <!-- Back to Stations page-->
	<form action="{% url 'stations' %}" method="GET">
		{% csrf_token %}
		<button type="submit">Back</button>
	</form>
</div>

<div class="pagination">
    <span class="step-links">
	{% if page_obj.has_previous %}
	    <a href="?page=1">&laquo; first</a>
	    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
	{% endif %}

	<span class="current">
	    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
	</span>

	{% if page_obj.has_next %}
	    <a href="?page={{ page_obj.next_page_number }}">next</a>
	    <a href="?page={{ page_obj.paginator.num_pages }}">kast &raquo;</a>
	{% endif %}
    </span>
</div>

{% endblock main %}

src/apps/stations/templates/station_instruments.html
{% extends "base_stations.html" %}

{% block title %}
  <h1 class="text-center">Station Instruments</h1>
{% endblock title %}

{% block main %}
{% load render_table from django_tables2 %}

<style>
table {
    width: 1000px;
}
#show_usr_btn {
    width: 130px;
}
</style>

<!-- Back button -->
<div style="padding-top: 10px;">
    <form action="{% url 'stations' %}" method="GET">
	<input type="hidden" name="swap" value="1">
        {% csrf_token %}
        <button type="submit">⬅ Back to Station List</button>
    </form>
</div>

<br>

<!-- Render the table -->
<div>
    {% render_table table %}
</div>

<!-- Pagination -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock main %}

src/apps/stations/templates/test_table.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
	<head>
		<title>List of Stations</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
	</head>
	<body>
		{% render_table table %}
	</body>
</html>